// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The eBay Buy Browse API lets applications search for items by keyword, category, GTIN or image, retrieve item details, and check item compatibility.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.ebay.com/buy/browse/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Search items
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Summaries of items matching the search criteria 
    remote isolated function searchItems(SearchItemsHeaders headers = {}, *SearchItemsQueries queries) returns SearchPagedCollection|error {
        string resourcePath = string `/item_summary/search`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Search items by image
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - The container for the image information fields 
    # + return - Summaries of items matching the image 
    remote isolated function searchItemsByImage(SearchItemsByImageHeaders headers, SearchByImageRequest payload, *SearchItemsByImageQueries queries) returns SearchPagedCollection|error {
        string resourcePath = string `/item_summary/search_by_image`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get item
    #
    # + itemId - This path parameter specifies the unique RESTful identifier of the item being retrieved.
    # RESTful Item ID Format: v1|#|#
    # For a single SKU listing, pass in the item ID:
    # v1|2**********2|0
    # For a multi-SKU listing, pass in the identifier of the variation:
    # v1|1**********2|4**********2
    # For more information about item IDs for RESTful APIs, refer to Item ID legacy API compatibility overview in the Buying Integration Guide
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Details of the requested item 
    remote isolated function getItem(string itemId, GetItemHeaders headers = {}, *GetItemQueries queries) returns Item|error {
        string resourcePath = string `/item/${getEncodedUri(itemId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get item by legacy ID
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Details of the item matching the legacy ID 
    remote isolated function getItemByLegacyId(GetItemByLegacyIdHeaders headers = {}, *GetItemByLegacyIdQueries queries) returns Item|error {
        string resourcePath = string `/item/get_item_by_legacy_id`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get multiple items
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Details of the requested items 
    remote isolated function getItems(GetItemsHeaders headers = {}, *GetItemsQueries queries) returns Items|error {
        string resourcePath = string `/item/`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get items by item group
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Items belonging to the requested item group 
    remote isolated function getItemsByItemGroup(GetItemsByItemGroupHeaders headers = {}, *GetItemsByItemGroupQueries queries) returns ItemGroup|error {
        string resourcePath = string `/item/get_items_by_item_group`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Check item compatibility
    #
    # + itemId - This path parameter specifies the unique RESTful identifier of an item (such as the park you want to check).
    # RESTful Item ID Format: v1|#|#
    # For a single SKU listing, pass in the item ID:
    # v1|2**********2|0
    # For a multi-SKU listing, pass in the identifier of the variation:
    # v1|1**********2|4**********2
    # For more information about item IDs for RESTful APIs, refer to Item ID legacy API compatibility overview in the Buying Integration Guide
    # + headers - Headers to be sent with the request 
    # + payload - Product compatibility details to check against the item 
    # + return - Compatibility check result for the item and the given product 
    remote isolated function checkCompatibility(string itemId, CheckCompatibilityHeaders headers, CompatibilityPayload payload) returns CompatibilityResponse|error {
        string resourcePath = string `/item/${getEncodedUri(itemId)}/check_compatibility`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
